services:
  backend:
    build: ./backend
    container_name: chordchart_pro_backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
    env_file:
      - .env  # Carrega as variáveis do arquivo .env
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    container_name: chordchart_pro_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge