version: '3.8'

services:
  backend:
    build: ./backend
    container_name: chordchart_pro_backend_prod
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - chordchart_data:/app/data
    env_file:
      - .env
    networks:
      - app-network
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/check_auth"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: nginx:alpine
    container_name: chordchart_pro_frontend_prod
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app:/usr/share/nginx/html:ro
      - ./nginx-cloudflare.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  chordchart_data:
    driver: local

networks:
  app-network:
    driver: bridge 